name: SimpleDupe
version: 1.0
main: com.skitmc.simpledupe.SimpleDupe
api-version: 1.20
author: Skitxoe
description: A lightweight, customizable item duplication plugin.

commands:
  dupe:
    description: Duplicates the item in your main hand.
  simpledupereload:
    description: Reloads the SimpleDupe configurations and messages.
    aliases: [dupereload]

permissions:
  simpledupe.use:
    description: Allows players to duplicate items using /dupe.
    default: true
  simpledupe.admin:
    description: Allows admins to reload the plugin configuration using /simpledupereload.
    default: op